<a href="https://colab.research.google.com/github/mwaldrop1/mwaldrop1/blob/main/AItrainingday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!uname -r

6.1.123+


In [3]:
!cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [8]:
!python3 -V

Python 3.11.12


In [10]:
df=pd.read_csv('https://raw.githubusercontent.com/redashu/Datasets/refs/heads/master/all_month.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9593 entries, 0 to 9592
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   time             9593 non-null   object 
 1   latitude         9593 non-null   float64
 2   longitude        9593 non-null   float64
 3   depth            9593 non-null   float64
 4   mag              9592 non-null   float64
 5   magType          9592 non-null   object 
 6   nst              8018 non-null   float64
 7   gap              8018 non-null   float64
 8   dmin             8017 non-null   float64
 9   rms              9592 non-null   float64
 10  net              9593 non-null   object 
 11  id               9593 non-null   object 
 12  updated          9593 non-null   object 
 13  place            9593 non-null   object 
 14  type             9593 non-null   object 
 15  horizontalError  7317 non-null   float64
 16  depthError       9592 non-null   float64
 17  magError      

In [11]:
#define features and label
features = ['latitude','longitude','depth']
target = 'mag'
#dropping missing value
df=df.dropna(subset=[target])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9592 entries, 0 to 9592
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   time             9592 non-null   object 
 1   latitude         9592 non-null   float64
 2   longitude        9592 non-null   float64
 3   depth            9592 non-null   float64
 4   mag              9592 non-null   float64
 5   magType          9592 non-null   object 
 6   nst              8017 non-null   float64
 7   gap              8017 non-null   float64
 8   dmin             8016 non-null   float64
 9   rms              9591 non-null   float64
 10  net              9592 non-null   object 
 11  id               9592 non-null   object 
 12  updated          9592 non-null   object 
 13  place            9592 non-null   object 
 14  type             9592 non-null   object 
 15  horizontalError  7316 non-null   float64
 16  depthError       9591 non-null   float64
 17  magError         79

In [14]:
#prepare data
X = df[features]
Y = df[target]
# printing x and y
print(X.head())
print(y.head())

    latitude   longitude  depth
0  38.840668 -122.834335   1.32
1  61.556800 -141.271600  13.40
2  61.789200 -149.608200  38.70
3  60.081400 -152.528700  97.80
4  35.639833 -117.548500   8.08
0    0.53
1    1.20
2    1.20
3    1.40
4    0.89
Name: mag, dtype: float64


In [20]:
# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
# printing scaled features
print(X_scaled)

[[0.68435702 0.15879891 0.00739493]
 [0.83742182 0.10757995 0.02592828]
 [0.83898777 0.08442076 0.06474399]
 ...
 [0.7240133  0.19133964 0.0090212 ]
 [0.03662389 0.90931204 0.02071194]
 [0.68785973 0.19113453 0.00443389]]


In [21]:
#split data for training and testing 80/20 ratio
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
#normalize features
scaler = MinMaxScaler()
X_scaled
